Repository gautambaghel/terraform-google-terraform-cloud-agents, pull requests merged in 2023-06, with the labels that each got.

#1 Various docs updates
  CONTRIBUTING.md
  README.md
  examples/tfc-agent-gke-simple/README.md
  examples/tfc-agent-mig-container-vm-simple/README.md
  examples/tfc-agent-mig-vm-simple/README.md
  modules/tfc-agent-gke/README.md
  modules/tfc-agent-mig-container-vm/README.md
  modules/tfc-agent-mig-vm/README.md
Labels: documentation

#3 Fix variable defaults
  modules/tfc-agent-gke/variables.tf
  modules/tfc-agent-mig-container-vm/main.tf
  modules/tfc-agent-mig-container-vm/variables.tf
  modules/tfc-agent-mig-vm/variables.tf
Labels: bug

#4 Terraform Cloud Agent hardcoded version fix
  modules/tfc-agent-mig-vm/main.tf
  modules/tfc-agent-mig-vm/scripts/startup.sh
  modules/tfc-agent-mig-vm/variables.tf
Labels: enhancement
